### ISSUE TITLE
error running ae_fetch

### ISSUE THREAD

**Issue by fesnakm** [wtee/alma_enumerator#2]
I'm guessing I'm missing some info that isn't in the readme, but I filled in the api key, added in an mms ID, and tried adding blank text files output.txt, input.txt, and error.txt for those sections, and also tried with no text files for output, input and error. installed and updated all the dependencies, python version 3.12, requests version 2.31.0, beautifulsoup 4.12.2. not sure what to do (tried running in vscode and cmd).

PS C:\Users\fesnakm> & C:/Users/fesnakm/AppData/Local/Programs/Python/Python312/python.exe c:/Users/fesnakm/alma_enumerator-master/ae_fetch
Traceback (most recent call last):
  File "c:\Users\fesnakm\alma_enumerator-master\ae_fetch", line 30, in <module>
    fetch(mms_id, output_file, error_file, api_key, base_url)
  File "c:\Users\fesnakm\alma_enumerator-master\AE.py", line 414, in fetch
    holdings = get_holdings(base_url, mms_id, api_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fesnakm\alma_enumerator-master\AE.py", line 20, in get_holdings
    soup = BeautifulSoup(r.text, 'xml')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fesnakm\AppData\Local\Programs\Python\Python312\Lib\site-packages\bs4\__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

**Comment by fesnakm** [comment]
ran 

pip install html5lib
pip install lxml

in addition to checking to make sure bs4 was installed and resolved this issue
